Bservices:
  bluesteel:
    build: ./bluesteel
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  restile:
    build: ./restile
    ports:
      - "5173:5173"

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: bluesteel
      POSTGRES_PASSWORD: bluesteel_pw
      POSTGRES_DB: bluesteel_db
    volumes:
      - db:/var/lib/postgresql
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: unless-stopped

volumes:
  db: